<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE userLogin [
<!ELEMENT userLogin (user)+>
<!ELEMENT user (username , password , email, dob, mobile, type)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT type (#PCDATA)>
]>

<userLogin>
	<user>
		<username>rakib</username>
		<password>a36949228c1d9146cace6359d88968e8</password>
		<email>rakib@aiub.edu</email>
		<dob>01/01/2000</dob>
		<mobile>01254863254</mobile>
		<type>customer</type>
	</user>
</userLogin>